Failing Pipeline Test

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -13,5 +13,9 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
+
+      - name: To Show Error
+        run: echo "Should fail at this point ...." ; exit 1
+
       - name: Run a one-line script
         run: echo "Continuous Integration"
